title: "Mariona & Gonzalo's Wedding"
description: "Join us to celebrate Mariona & Gonzalo's love!"
theme: jekyll-theme-cayman  # Optional: Choose any GitHub Pages-compatible theme
show_downloads: false
